-- CTO spec: adds a new restricted, site-facing company role.
--
-- Standalone migration, deliberately not combined with anything that
-- references the new value -- Postgres forbids using a newly-added enum
-- value in the same transaction that adds it (ALTER TYPE ... ADD VALUE
-- commits its own implicit transaction boundary). Same pattern already
-- used by 028_rfi_workflow.sql, 058_rfi_approve_permission.sql,
-- 059_snag_verify_permission.sql for other enums.
--
-- 'construction_manager' already exists in this enum (since 001) as a
-- normal, unrestricted company role -- it is being deliberately redefined
-- (restricted) in application code as part of this same change, not
-- renamed here, per explicit product decision. No enum change needed for
-- it. 'site_engineer' is NOT added here either: the restricted "Site
-- Engineer" identity reuses the EXISTING project_members.role enum value
-- of the same name (a different, per-project dimension, untouched by this
-- migration) rather than becoming a new company-wide role.
ALTER TYPE company_role_enum ADD VALUE IF NOT EXISTS 'project_engineer';
