import type { HelpArticle } from './types';

// Verified against AssistantPage.tsx and AiSettingsPage.tsx directly.
export const aiAssistantArticles: HelpArticle[] = [
  {
    slug: 'opening-the-ai-assistant',
    category: 'ai-assistant',
    title: 'Opening the AI Assistant',
    summary: 'Where to find the AI Assistant and how it relates to the project you\'re in.',
    whatItDoes: 'A chat interface scoped to the project you open it from -- it can see and discuss that project\'s own RFIs, issues, snagging, risk, progress, and documents, but not other projects.',
    whoCanUse: 'Any project member.',
    steps: ['Open a project and select "AI Assistant" in the sidebar.'],
    relatedSlugs: ['asking-platform-related-questions', 'understanding-ai-limitations'],
    keywords: ['ai assistant', 'chatbot'],
  },
  {
    slug: 'asking-platform-related-questions',
    category: 'ai-assistant',
    title: 'Asking Platform-Related Questions',
    summary: 'What kinds of questions the assistant can actually help with.',
    whatItDoes: 'Answers questions grounded in this project\'s own data -- for example, "how many open high-priority issues are assigned to me," or "summarize the RFIs still awaiting a response." It can also draft (never submit) a new RFI, issue, or snag item for you to review and send through the normal form.',
    whenToUse: 'When you want a quick answer about this project\'s own records, or help getting started on a new RFI/issue/snag.',
    steps: [
      'Type your question and select send.',
      'If the assistant offers a draft, select "Review draft" to open it in the normal creation form, pre-filled -- you still edit and submit it yourself.',
    ],
    relatedSlugs: ['understanding-supported-ai-capabilities', 'understanding-ai-limitations'],
    keywords: ['ai question', 'ask assistant'],
  },
  {
    slug: 'understanding-supported-ai-capabilities',
    category: 'ai-assistant',
    title: 'Understanding Supported Capabilities',
    summary: 'What the assistant can do, in plain terms.',
    whatItDoes: 'Answers questions about this project\'s RFIs, issues, snagging, risk, progress, and documents, and can draft an RFI, issue, or snag item. If you reached it via "Ask AI about this" from a specific record, follow-up questions can refer to that record directly without you having to name it again.',
    requiredPermissions: 'A daily request quota applies, shown at the top of the Assistant page -- the exact limit depends on your company role.',
    relatedSlugs: ['understanding-ai-limitations'],
    keywords: ['ai capabilities'],
  },
  {
    slug: 'understanding-ai-limitations',
    category: 'ai-assistant',
    title: 'Understanding AI Limitations',
    summary: 'What the assistant deliberately will not do.',
    whatItDoes: 'Questions unrelated to this project\'s own data (general knowledge, other projects, anything off-topic) are blocked rather than answered, shown as a warning banner in the chat. The assistant never submits a draft on your behalf -- you always review and send it yourself through the normal form. It never auto-approves, auto-closes, or auto-assigns anything.',
    commonMistakes: ['Asking about a different project -- the assistant only ever sees the one you opened it from.'],
    relatedSlugs: ['understanding-supported-ai-capabilities', 'troubleshooting-ai-not-responding'],
    keywords: ['ai limitations'],
  },
  {
    slug: 'protecting-confidential-project-information',
    category: 'ai-assistant',
    title: 'Protecting Confidential Project Information',
    summary: 'What happens to your questions and this project\'s data.',
    whatItDoes: 'Your questions and the project data the assistant reads to answer them are sent to the AI provider configured for your account -- either EngineeringOS\'s own default provider, or, if you\'ve connected one yourself under "AI Provider" settings, your own OpenAI-compatible, Ollama, or custom endpoint.',
    commonMistakes: ['Pasting information into a question that you wouldn\'t want sent to whichever AI provider is active for your account.'],
    relatedSlugs: ['understanding-ai-limitations'],
    keywords: ['ai privacy', 'confidential information'],
  },
  {
    slug: 'reporting-incorrect-ai-responses',
    category: 'ai-assistant',
    title: 'Reporting Incorrect AI Responses',
    summary: 'There is currently no in-app way to flag an AI answer as wrong.',
    whatItDoes: 'If the assistant gives an answer that looks incorrect, there is no feedback button in the chat itself -- report it to your company admin directly.',
    notYetAvailable: true,
    relatedSlugs: ['understanding-ai-limitations'],
    keywords: ['report ai error', 'ai feedback'],
  },
  {
    slug: 'troubleshooting-ai-not-responding',
    category: 'ai-assistant',
    title: 'Troubleshooting AI Access',
    summary: 'The assistant doesn\'t answer, or shows a blocked/limit message.',
    troubleshootingSteps: [
      { problem: 'A warning banner appears instead of an answer', likelyCause: 'The question was judged off-topic for this project, or you\'ve reached your daily request limit (shown at the top of the page).', fix: 'Rephrase the question to be specifically about this project\'s own RFIs, issues, snagging, risk, progress, or documents. If you\'ve hit the daily limit, try again the next day.' },
      { problem: 'Using a connected custom AI provider and getting errors', likelyCause: 'The custom endpoint is unreachable or misconfigured.', fix: 'Check the connection under "AI Provider" settings, or switch back to the default provider.' },
    ],
    relatedSlugs: ['understanding-ai-limitations'],
    keywords: ['ai not responding', 'ai error'],
  },
];
