import type { HelpArticle } from './types';

// Verified against issues.controller.ts, issues.service.ts,
// snagging.controller.ts, IssueFormModal.tsx, SnagItemFormModal.tsx, and
// IssueDetail.tsx/SnagDetail.tsx directly. One correction worth flagging
// for anyone extending this file: editing an existing issue requires the
// "manage_issues" permission -- only *creating* a new one is open to
// every project member. It is easy to misread the controller and assume
// otherwise (this file's own audit did, on the first pass).
export const issuesSnaggingArticles: HelpArticle[] = [
  {
    slug: 'understanding-issues',
    category: 'issues-snagging',
    title: 'Understanding Issues',
    summary: 'What an Issue is and how its status moves from open to closed.',
    whatItDoes: 'An Issue records a problem on a project -- a defect, a safety concern, a punch-list item, or anything else worth tracking to resolution. It can be placed at a specific floor-plan location (see "Understanding Pinpoints") or raised without one.',
    whenToUse: 'For most problems found on a project. Use Snagging instead when the problem specifically needs an independent fixed→verified sign-off step.',
    whoCanUse: 'Any project member can create an issue. Editing one, or deleting it, requires the "manage_issues" permission (or being that project\'s Project Lead). Closing an issue has its own separate, stricter rule -- see "Reviewing and Closing an Issue."',
    relatedSlugs: ['creating-an-issue', 'reviewing-and-closing-an-issue', 'understanding-the-difference-between-issues-and-snagging'],
    keywords: ['issue', 'defect', 'punch list'],
  },
  {
    slug: 'creating-an-issue',
    category: 'issues-snagging',
    title: 'Creating an Issue',
    summary: 'How to raise a new issue.',
    whatItDoes: 'Creates a new issue against the current project.',
    whoCanUse: 'Any project member.',
    infoToEnter: ['Title', 'Description', 'Issue type', 'Priority', 'Discipline', 'Category (optional)', 'Assignee (optional)', 'Building/Level/Location (optional)', 'Deadline (optional)'],
    steps: [
      'Open the project\'s Issues page and select "+ New issue" (or raise one from a floor plan pin, or from the BIM viewer\'s "Raise issue" action, which pre-fills the camera view).',
      'Fill in the required fields and any optional ones that apply.',
      'Select "Create."',
    ],
    afterSubmission: 'The issue appears in the Issues list with a generated issue number, status "open" (or the equivalent legacy "open" state), and whatever priority/assignee you set.',
    whoIsNotified: 'The assignee, if one is set and isn\'t you.',
    commonMistakes: ['Leaving discipline unset when your company tracks issues by trade -- it can still be added later, but filtering by discipline won\'t find it until then.'],
    relatedSlugs: ['completing-required-issue-fields', 'assigning-issue-responsibility'],
    keywords: ['create issue', 'new issue', 'raise issue'],
  },
  {
    slug: 'completing-required-issue-fields',
    category: 'issues-snagging',
    title: 'Completing Required Fields',
    summary: 'What each field on the issue form means.',
    infoToEnter: [
      'Title -- a short, specific description.',
      'Description -- full detail.',
      'Issue type -- e.g. defect.',
      'Priority -- critical/high/medium/low.',
      'Discipline -- the trade or engineering discipline it falls under.',
      'Category -- a finer classification within the discipline.',
      'Building/Level/Location -- where on the project hierarchy it sits.',
      'Deadline -- when it needs resolving by.',
    ],
    relatedSlugs: ['creating-an-issue'],
    keywords: ['issue fields', 'issue form'],
  },
  {
    slug: 'assigning-issue-responsibility',
    category: 'issues-snagging',
    title: 'Assigning Responsibility',
    summary: 'Setting or changing who an issue is assigned to.',
    whatItDoes: 'Sets the project member responsible for resolving the issue. The assignee must already be a member of the project.',
    whoCanUse: 'Requires the "manage_issues" permission (or being Project Lead) to change on an existing issue; any project member can set it when first creating the issue.',
    whoIsNotified: 'The newly assigned person, if the assignment changes.',
    relatedSlugs: ['creating-an-issue'],
    keywords: ['assign issue', 'assignee'],
  },
  {
    slug: 'setting-issue-priority',
    category: 'issues-snagging',
    title: 'Setting Priority',
    summary: 'Marking an issue as critical, high, medium, or low priority.',
    whoCanUse: 'Set at creation by any project member; changed afterward by anyone with "manage_issues."',
    keywords: ['issue priority'],
  },
  {
    slug: 'adding-photographs-to-an-issue',
    category: 'issues-snagging',
    title: 'Adding Photographs',
    summary: 'Attaching a photo as evidence on an issue.',
    whatItDoes: 'Attaches a file to the issue as evidence. At least one such attachment is required before the issue can be closed (see "Reviewing and Closing an Issue").',
    whoCanUse: 'Any project member who can view the issue.',
    steps: ['Open the issue and use "Attach file" in its activity section.'],
    relatedSlugs: ['reviewing-and-closing-an-issue'],
    keywords: ['issue photo', 'attachment', 'evidence'],
  },
  {
    slug: 'adding-comments-to-an-issue',
    category: 'issues-snagging',
    title: 'Adding Comments',
    summary: 'Leaving a comment on an issue\'s activity log.',
    whoCanUse: 'Any project member who can view the issue.',
    steps: ['Open the issue, type into the comment box, and select "Send."'],
    whoIsNotified: 'The issue\'s current assignee, if they didn\'t write the comment themselves.',
    keywords: ['issue comment'],
  },
  {
    slug: 'updating-an-issue',
    category: 'issues-snagging',
    title: 'Updating an Issue',
    summary: 'Editing an existing issue\'s fields.',
    whatItDoes: 'Changes an issue\'s title, description, priority, discipline, category, location, assignee, or deadline.',
    requiredPermissions: '"manage_issues" permission, or being that project\'s Project Lead.',
    whoCanUse: 'Project members holding "manage_issues" (or the Project Lead) -- not every project member, unlike creating a new issue.',
    steps: ['Open the issue and select "Edit."'],
    whoIsNotified: 'The assignee, if the assignment changed.',
    relatedSlugs: ['understanding-issues'],
    keywords: ['edit issue', 'update issue'],
  },
  {
    slug: 'tracking-an-issue',
    category: 'issues-snagging',
    title: 'Tracking an Issue',
    summary: 'Following an issue\'s status and activity over time.',
    howToTrackProgress: 'An issue\'s status badge (open/in review/closed/reopened, or your company\'s equivalent naming) and its activity log (comments, status changes, forwards) on the issue\'s own detail page show its full history.',
    keywords: ['track issue', 'issue status'],
  },
  {
    slug: 'reviewing-and-closing-an-issue',
    category: 'issues-snagging',
    title: 'Reviewing and Closing an Issue',
    summary: 'Closing an issue requires evidence and a sufficiently senior role (or a specific project permission).',
    whatItDoes: 'Permanently closes an issue.',
    requiredPermissions: 'Company role Super Admin, Company Admin, Technical Director, or Engineering Manager -- or, for anyone else, the "manage_issues" project permission. A Project Lead who doesn\'t hold one of those roles or that permission cannot close an issue just by being Project Lead.',
    prerequisites: ['At least one evidence attachment (photo or other file) must already be on the issue.'],
    steps: ['Open the issue and select "Close" once the evidence requirement is met.'],
    afterSubmission: 'The issue\'s status becomes closed; it can be reopened later if needed.',
    commonMistakes: ['Trying to close an issue with no attachments -- the close action is rejected until at least one evidence file is present.'],
    relatedSlugs: ['adding-photographs-to-an-issue'],
    keywords: ['close issue', 'issue closure'],
  },
  {
    slug: 'understanding-the-difference-between-issues-and-snagging',
    category: 'issues-snagging',
    title: 'Understanding the Difference Between Issues and Snagging',
    summary: 'Issues close in one step; Snags close in two.',
    whatItDoes: 'An Issue moves through its status and closes once (by a sufficiently senior role, or someone granted "manage_issues", with evidence attached). A Snag additionally separates "marked as fixed" from "verified" -- two different actions, which can be done by two different people, so the person who fixed something isn\'t the one confirming their own fix.',
    relatedSlugs: ['understanding-issues', 'understanding-snagging'],
    keywords: ['issue vs snag'],
  },
  {
    slug: 'common-issue-reporting-mistakes',
    category: 'issues-snagging',
    title: 'Common Issue Reporting Mistakes',
    summary: 'Frequent mistakes when raising or managing issues.',
    commonMistakes: [
      'Not attaching a photo early -- it\'s required before the issue can ever be closed, so attaching it when you first raise the issue avoids a delay later.',
      'Assuming any project member can edit or close an issue -- editing needs "manage_issues"; closing needs a specific company role.',
      'Leaving the location/discipline fields blank, which makes the issue harder to find later with filters.',
    ],
    keywords: ['issue mistakes'],
  },
  {
    slug: 'understanding-snagging',
    category: 'issues-snagging',
    title: 'Understanding Snagging',
    summary: 'What a Snag is and its fixed → verified workflow.',
    whatItDoes: 'A Snag is a defect-tracking record with a two-step closure: whoever corrects the defect marks it "fixed"; someone with sign-off authority then marks it "verified." It can also be "voided" if it turns out not to be a real defect.',
    whoCanUse: 'Creating a snag is open to any project member. Editing, marking fixed/void, and most other actions require "manage_project_records" (or Project Lead). Verifying requires "manage_project_records" OR the narrower "verify_snag_items" permission.',
    relatedSlugs: ['creating-a-snag', 'verifying-a-snag'],
    keywords: ['snag', 'snagging'],
  },
  {
    slug: 'creating-a-snag',
    category: 'issues-snagging',
    title: 'Creating a Snag',
    summary: 'Raising a new snag item.',
    whoCanUse: 'Any project member.',
    infoToEnter: ['Title', 'Description', 'Priority', 'Trade', 'Location (free text)', 'Assignee', 'Due date'],
    steps: [
      'Open the project\'s Snagging page and select "+ New snag item" (or convert an existing floor-plan pin\'s issue to a snag).',
      'Fill in the fields and select "Create."',
    ],
    whoIsNotified: 'The assignee, if set.',
    relatedSlugs: ['understanding-snagging'],
    keywords: ['create snag', 'new snag'],
  },
  {
    slug: 'marking-a-snag-fixed',
    category: 'issues-snagging',
    title: 'Marking a Snag as Fixed',
    summary: 'The first of the two closure steps.',
    requiredPermissions: '"manage_project_records" permission, or Project Lead.',
    steps: ['Open the snag item and select "Mark as fixed."'],
    afterSubmission: 'Status becomes "fixed," ready for someone with sign-off authority to verify.',
    relatedSlugs: ['verifying-a-snag'],
    keywords: ['snag fixed'],
  },
  {
    slug: 'verifying-a-snag',
    category: 'issues-snagging',
    title: 'Verifying a Snag',
    summary: 'The second closure step -- independent sign-off that the fix is real.',
    requiredPermissions: '"manage_project_records" OR the narrower "verify_snag_items" permission.',
    steps: ['Open a "fixed" snag item and select "Verify."'],
    afterSubmission: 'Status becomes "verified" -- the snag is closed.',
    commonMistakes: ['Expecting the same person who marked it fixed to also be able to verify it without the right permission -- the two steps are deliberately separable by design, though this platform does not technically stop the same person doing both if they hold both permissions.'],
    relatedSlugs: ['marking-a-snag-fixed'],
    keywords: ['snag verify'],
  },
];
