import type { HelpArticle } from './types';

// Email integration content verified against the actual Phase 3
// implementation (EmailSettingsPage.tsx, EmailComposerModal.tsx,
// EmailHistoryList.tsx, outlook/gmail integration services) -- not
// assumed. Notification content verified against NotificationBell.tsx
// (no preferences UI exists there).
export const notificationsEmailArticles: HelpArticle[] = [
  {
    slug: 'opening-a-notification',
    category: 'notifications-email',
    title: 'Opening a Notification',
    summary: 'Viewing and jumping to a notification\'s record.',
    whoCanUse: 'Any signed-in user, for their own notifications.',
    steps: ['Select the bell icon in the sidebar.', 'Select a notification to open the record it relates to.'],
    relatedSlugs: ['understanding-notifications'],
    keywords: ['notification', 'bell'],
  },
  {
    slug: 'managing-notification-preferences',
    category: 'notifications-email',
    title: 'Managing Notification Preferences',
    summary: 'There is currently no settings page for notification preferences.',
    whatItDoes: 'Every user receives the same set of notification types (assignment, reassignment, new comment on an assigned record, forwarding) -- there is no per-user setting to mute or customize them.',
    notYetAvailable: true,
    relatedSlugs: ['understanding-notifications'],
    keywords: ['notification preferences', 'mute notifications'],
  },
  {
    slug: 'connecting-outlook',
    category: 'notifications-email',
    title: 'Connecting Outlook',
    summary: 'Authorizing EngineeringOS to send email from your own Outlook/Microsoft 365 account.',
    whatItDoes: 'Connects your own Microsoft mailbox so you can send project email from your real address. EngineeringOS only requests permission to send mail as you (and to confirm which address you connected) -- it never requests permission to read your mailbox.',
    whenToUse: 'Before using the "Email" button on a project, RFI, Issue, Submittal, or Snag page, if you want to send from Outlook.',
    whoCanUse: 'Any signed-in user, for their own mailbox only -- not something a company admin sets up on someone else\'s behalf.',
    steps: [
      'Open "Email Integration" in the sidebar.',
      'Select "Connect Outlook."',
      'Sign in to Microsoft and accept the permissions requested.',
    ],
    afterSubmission: 'You\'re redirected back to Email Integration, showing your connected Outlook address and a "Connected" status.',
    troubleshootingSteps: [
      { problem: 'Redirected back with a "failed" or "declined" status', likelyCause: 'A permission was declined, or a transient error during the Microsoft handshake.', fix: 'Try connecting again and accept every permission requested.' },
    ],
    relatedSlugs: ['sending-project-emails', 'disconnecting-an-email-account'],
    keywords: ['outlook', 'microsoft 365', 'connect email'],
  },
  {
    slug: 'connecting-gmail',
    category: 'notifications-email',
    title: 'Connecting Gmail',
    summary: 'Authorizing EngineeringOS to send email from your own Gmail/Google Workspace account.',
    whatItDoes: 'Connects your own Google mailbox so you can send project email from your real address. Only send permission and your email address are requested -- never read access to your mailbox.',
    whoCanUse: 'Any signed-in user, for their own mailbox only.',
    steps: [
      'Open "Email Integration" in the sidebar.',
      'Select "Connect Gmail."',
      'Sign in to Google and accept the permissions requested.',
    ],
    afterSubmission: 'You\'re redirected back showing your connected Gmail address and a "Connected" status.',
    commonMistakes: ['If your company\'s Google Workspace hasn\'t verified this app yet, you may see an "unverified app" warning during consent -- this is a Google-side verification status, not a sign the connection is unsafe; check with your company admin if you\'re unsure whether to proceed.'],
    relatedSlugs: ['sending-project-emails', 'disconnecting-an-email-account'],
    keywords: ['gmail', 'google', 'connect email'],
  },
  {
    slug: 'sending-project-emails',
    category: 'notifications-email',
    title: 'Sending Project Emails',
    summary: 'Composing and sending email from your connected mailbox, linked to a project record.',
    whatItDoes: 'Opens a compose window to send email from your connected Outlook or Gmail account. Recipients, subject, message, and attachments are all entered by you -- nothing is sent automatically. If you open it from an RFI, Issue, Submittal, or Snag page, the subject is pre-filled with that record\'s reference and the sent email is automatically associated with it; sending never changes that record\'s own status.',
    whenToUse: 'Whenever you need to email someone outside EngineeringOS about a specific project record, and want a record of it kept against that record.',
    whoCanUse: 'Any member of the project, provided they have connected at least one mailbox (Outlook or Gmail).',
    prerequisites: ['A connected Outlook or Gmail account.'],
    infoToEnter: ['To (one or more recipients)', 'CC / BCC (optional)', 'Subject', 'Message', 'Attachments (optional, from files already uploaded to the project)'],
    steps: [
      'Open a project (or a specific RFI/Issue/Submittal/Snag record) and select "Email."',
      'Fill in recipients, subject, and message.',
      'Attach files if needed.',
      'Select "Send."',
    ],
    afterSubmission: 'The email is sent from your own mailbox and a record of it (sender, recipients, subject, timestamp, and whether it succeeded -- never the message body) is kept in that project\'s email history.',
    whoIsNotified: 'Only the external recipients you entered -- EngineeringOS does not notify anyone inside the platform about an email you send.',
    commonMistakes: ['Trying to send without a connected mailbox -- connect one first under Email Integration.'],
    relatedSlugs: ['connecting-outlook', 'connecting-gmail', 'understanding-email-history'],
    keywords: ['send email', 'compose email'],
  },
  {
    slug: 'understanding-email-history',
    category: 'notifications-email',
    title: 'Understanding Email History',
    summary: 'A metadata-only audit trail of emails sent through EngineeringOS.',
    whatItDoes: 'Shows who sent an email, from which address, to whom, when, the subject, and whether it succeeded -- never the message body, which is never stored. Visible both as a project-wide log and, filtered to just that record, on the RFI/Issue/Submittal/Snag page it was sent about.',
    whoCanUse: 'Any member of the project the email was sent on behalf of.',
    howToTrackProgress: 'Open "Email History" from a project, or scroll to the "Email History" section on a specific record\'s page.',
    relatedSlugs: ['sending-project-emails'],
    keywords: ['email history', 'sent emails'],
  },
  {
    slug: 'disconnecting-an-email-account',
    category: 'notifications-email',
    title: 'Disconnecting an Email Account',
    summary: 'Revoking EngineeringOS\'s access to your mailbox.',
    whoCanUse: 'Any signed-in user, for their own connected mailbox.',
    steps: ['Open "Email Integration," find the connected provider, and select "Disconnect."'],
    afterSubmission: 'The stored, encrypted connection is removed; you can no longer send from that provider until reconnecting. Past email history is not deleted.',
    relatedSlugs: ['connecting-outlook', 'connecting-gmail'],
    keywords: ['disconnect email'],
  },
  {
    slug: 'troubleshooting-email-authorization',
    category: 'notifications-email',
    title: 'Troubleshooting Email Authorization',
    summary: 'Connecting Outlook or Gmail fails or shows an error.',
    troubleshootingSteps: [
      { problem: 'Connection fails or shows "failed" after the consent screen', likelyCause: 'A required permission was declined, or a transient provider error.', fix: 'Try connecting again from Email Integration settings and accept every permission requested.' },
      { problem: '"Test connection" reports the connection is no longer valid', likelyCause: 'The provider-side authorization was revoked (e.g. by your IT admin, or because your password changed).', fix: 'Disconnect and reconnect that provider.' },
    ],
    relatedSlugs: ['connecting-outlook', 'connecting-gmail'],
    keywords: ['email connection failed'],
  },
];
