import type { HelpArticle } from './types';

// Verified against rfis.controller.ts and RfiFormModal.tsx directly.
export const rfiArticles: HelpArticle[] = [
  {
    slug: 'understanding-rfi',
    category: 'rfi',
    title: 'Understanding RFI',
    summary: 'What an RFI is and how it moves from draft to closed.',
    whatItDoes: 'An RFI (Request for Information) is a formal question raised against a project. It moves through a workflow: created (draft) → submitted → responded → optionally sent for review (PMC/client sign-off) → closed. It can be sent back for clarification at various points, and a closed RFI can be reopened.',
    whoCanUse: 'Any project member can create and submit their own RFI. Responding, sending for review, deciding a review, and closing require specific permissions -- see the individual action articles.',
    relatedSlugs: ['creating-an-rfi', 'submitting-an-rfi', 'tracking-rfi-status'],
    keywords: ['rfi', 'request for information'],
  },
  {
    slug: 'creating-an-rfi',
    category: 'rfi',
    title: 'Creating an RFI',
    summary: 'How to raise a new RFI.',
    whatItDoes: 'Creates a new RFI in draft status.',
    whoCanUse: 'Any project member.',
    infoToEnter: [
      'Subject',
      'Question',
      'Priority',
      'Discipline',
      'Cost impact (none/potential/yes/to be determined, with amount and description if applicable)',
      'Time impact (same four-state scale, with days and description if applicable)',
      'Drawing/model impact (same four-state scale, with an owner for the follow-up if applicable)',
      'Assignee (optional)',
      'Due date (optional)',
    ],
    steps: [
      'Open the project\'s RFIs page and select "+ New RFI."',
      'Fill in the subject and question, then set priority and discipline.',
      'Set cost/time/drawing impact if relevant.',
      'Select "Create."',
    ],
    afterSubmission: 'The RFI is created in draft status with a generated RFI number, visible only to the project -- it is not yet submitted.',
    relatedSlugs: ['writing-a-clear-rfi-description', 'submitting-an-rfi'],
    keywords: ['create rfi', 'new rfi'],
  },
  {
    slug: 'writing-a-clear-rfi-description',
    category: 'rfi',
    title: 'Writing a Clear RFI Description',
    summary: 'Tips for a question that gets answered quickly.',
    commonMistakes: [
      'Asking multiple unrelated questions in one RFI -- split them so each can be answered and closed independently.',
      'Omitting the specific drawing/spec reference the question relates to.',
    ],
    relatedSlugs: ['creating-an-rfi'],
    keywords: ['rfi description'],
  },
  {
    slug: 'attaching-supporting-documents-to-rfi',
    category: 'rfi',
    title: 'Attaching Supporting Documents',
    summary: 'Adding drawings, photos, or calculation sheets to an RFI.',
    requiredPermissions: '"manage_project_records" permission, or being that project\'s Project Lead.',
    steps: ['Open the RFI and use its attachment upload control.'],
    attachments: 'Any supporting file -- drawing excerpt, photo, calculation sheet.',
    relatedSlugs: ['creating-an-rfi'],
    keywords: ['rfi attachment'],
  },
  {
    slug: 'submitting-an-rfi',
    category: 'rfi',
    title: 'Submitting an RFI',
    summary: 'Moving an RFI from draft to submitted.',
    whatItDoes: 'Submits a draft RFI, making it active and visible as awaiting a response.',
    requiredPermissions: 'The RFI\'s own creator, OR "manage_rfis," OR being that project\'s Project Lead, OR super admin.',
    steps: ['Open the draft RFI and select "Submit."'],
    whoIsNotified: 'Whoever is responsible for responding, per your project\'s own convention (there is no separate "recipient" field enforced by the system beyond assignment).',
    relatedSlugs: ['creating-an-rfi', 'tracking-rfi-status'],
    keywords: ['submit rfi'],
  },
  {
    slug: 'responding-to-an-rfi',
    category: 'rfi',
    title: 'Responding to an RFI',
    summary: 'Recording the formal answer to a submitted RFI.',
    requiredPermissions: '"manage_rfis" permission.',
    whoCanUse: 'Project members holding "manage_rfis" (or Project Lead/super admin, which pass every permission check).',
    steps: ['Open the submitted RFI and select "Respond."', 'Enter the answer.'],
    afterSubmission: 'Status becomes "responded." If drawing/model impact was marked "yes," the drawing-update tracking fields become relevant (see "Understanding RFI Closure").',
    relatedSlugs: ['understanding-rfi-closure', 'tracking-rfi-status'],
    keywords: ['respond rfi', 'rfi answer'],
  },
  {
    slug: 'tracking-rfi-status',
    category: 'rfi',
    title: 'Tracking RFI Status',
    summary: 'Following an RFI through its workflow.',
    howToTrackProgress: 'The RFI list shows each RFI\'s current status (draft/submitted/responded/under review/closed/etc.) and priority; the RFI\'s own detail page shows its full stamp history (query/answer) and, if drawing impact applies, whether the drawing update has been applied and sent to site.',
    relatedSlugs: ['understanding-rfi'],
    keywords: ['rfi status', 'rfi tracking'],
  },
  {
    slug: 'understanding-rfi-closure',
    category: 'rfi',
    title: 'Understanding RFI Closure',
    summary: 'How an RFI gets closed, with or without a review step.',
    whatItDoes: 'An RFI can be closed directly (requires "manage_rfis") once responded, or routed through a review step first: sent to a stakeholder (e.g. PMC or client) for sign-off, who then approves it (which closes it) or rejects it (which sends it back for clarification).',
    requiredPermissions: 'Direct close: "manage_rfis". Submit-for-review and decide-review: "manage_rfis" OR the narrower "approve_rfis".',
    reviewEditApproveClose: 'A reviewer holding "approve_rfis" can approve or reject a review without needing the broader "manage_rfis" permission -- this lets a PMC/client reviewer sign off without being able to edit or close other RFIs outright.',
    relatedSlugs: ['responding-to-an-rfi'],
    keywords: ['rfi closure', 'rfi review', 'rfi approval'],
  },
  {
    slug: 'common-rfi-mistakes',
    category: 'rfi',
    title: 'Common RFI Mistakes',
    summary: 'Frequent mistakes when raising or managing RFIs.',
    commonMistakes: [
      'Forgetting to submit a drafted RFI -- it stays invisible to anyone expecting to respond until submitted.',
      'Marking drawing impact "yes" without actually following up -- the drawing-update tracking fields exist specifically so this doesn\'t get lost.',
      'Expecting to close an RFI without the "manage_rfis" permission.',
    ],
    keywords: ['rfi mistakes'],
  },
];
